name: docker-compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        env:
          DB_USER_NAME: test
          DB_USER_PW: test
          DB_ROOT_PW: root
          DB_HOST: db-server
          DB_NAME: d-anime-mylist
          TZ: Asia/Tokyo
        run: |
          chmod -R 777 d-anime-mylist-backend/
