name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9.13"]
        poetry-version: ["1.1.13"]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: ls
        run: ls
      - name: build
        run: |
          cd src/OS-lecture-Support-tool/
          poetry build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: release
